---
title: "FeatureCheckwStans"
author: "wkumler"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(data.table)

ms_files <- c("G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Blk_KM1906U14-Blk_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Full1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Full2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Full3.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Half1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Half2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Poo_TruePooFK180310_Half3.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-25m_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-25m_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-25m_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-DCM_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-DCM_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S62C1-DCM_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-25m_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-25m_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-25m_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-DCM_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-DCM_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S64C1-DCM_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-25m_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-25m_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-25m_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-DCM_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-DCM_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S77C1-DCM_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-25m_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-25m_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-25m_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-DCM_A.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-DCM_B.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Smp_FK180310S80C1-DCM_C.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix1InH2O_1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix1InH2O_2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix1InMatrix_1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix1InMatrix_2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix2InH2O_1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix2InH2O_2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix2InMatrix_1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_4uMStdsMix2InMatrix_2.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_H2OinMatrix_1.mzML", 
"G:\\My Drive\\FalkorFactor\\mzMLs\\190715_Std_H2OinMatrix_2.mzML"
)

grabSingleFileData <- function(filename){
  msdata <- mzR:::openMSfile(filename)
  fullhd <- mzR::header(msdata)
  spectra_list <- lapply(seq_len(nrow(fullhd)), function(x){
    given_peaks <- mzR::peaks(msdata, x)
    rtime <- fullhd[x, "retentionTime"]
    return(cbind(rtime, given_peaks))
  })
  all_data <- `names<-`(as.data.frame(do.call(rbind, spectra_list)), 
                        c("rt", "mz", "int"))
  return(all_data)
}
```


```{r}
stans_df <- read.csv(file = "falkor_stans.csv", stringsAsFactors = FALSE) %>%
  filter(Fraction1=="HILICPos")
molecule_guesses <- read.csv("temp_data/molecule_guesses.csv", stringsAsFactors = FALSE)
peak_df <- read.csv("temp_data/peaks_isoadded.csv", stringsAsFactors = FALSE)
raw_data <- lapply(ms_files, grabSingleFileData)
raw_data <- lapply(seq_along(raw_data), function(x){
  cbind(fileid=basename(ms_files)[x], raw_data[[x]])
})
raw_data <- do.call(rbind, raw_data)
raw_data <- raw_data[raw_data$rt>60&raw_data$rt<1100,]
saveRDS(raw_data, file = "MS1_data_frame_all")
MS1_data <- readRDS("MS1_data_frame_all")
MS1_data$fileid <- as.character(MS1_data$fileid)
MS1_dt <- as.data.table(MS1_data)

metadata <- data.frame(
  fileid=basename(ms_files),
  sample_group=c("Blank", "Pooled", "Sample", "Std")[c(1, rep(2, 6), rep(3, 24), rep(4, 10))],
  depth=c("Blank", "Pooled", "DCM", "25m", "Std")[c(1, rep(2, 6), rep(c(rep(3, 3), rep(4, 3)), 4), rep(5, 10))],
  spindir=c("Blank", "Pooled", "Cyclone", "Anticyclone", "Std")[c(1, rep(2, 6), rep(3, 12), rep(4, 12), rep(5, 10))],
  time=c("Blank", "Pooled", "Morning", "Afternoon", "Std")[c(1, rep(2, 6), rep(c(rep(3, 6), rep(4, 6)), 2), rep(5, 10))], stringsAsFactors = FALSE
)

pmppm <- function(mass, ppm=4){c(mass*(1-ppm/1000000), mass*(1+ppm/1000000))}
```


## For each STANDARD

Check on peak quality, annotation, and identification

```{r}
for(i in seq_len(nrow(stans_df))){
  mass_i <- as.numeric(stans_df[i, "m.z"])
  eic <- MS1_dt[mz%between%pmppm(mass_i, ppm = 5)]
  eic_metadata <- left_join(eic, metadata, by="fileid")
  chosen_peaks <- peak_df %>% filter(mz%between%pmppm(mass_i, ppm = 5))
  gp <- ggplot() + 
    geom_line(data = eic_metadata, 
              aes(x=rt, y=int, group=fileid, color=depth)) +
    scale_color_manual(values = c("25m"="#0000FF99", "Blank"="#FF000099", 
                                  "DCM"="#00FF0099", "Pooled"="#00000099",
                                  "Std"="#00000099"), 
                       name="Depth") +
    geom_vline(data = chosen_peaks, aes(xintercept = rtmin), col="red") +
    geom_vline(data = chosen_peaks, aes(xintercept = rtmax), col="red") +
    theme_bw() + ggtitle(stans_df[i, "Compound.Name"])
  print(gp)
  
  other_stans <- stans_df %>%
    filter(stans_df$m.z%between%pmppm(mass_i, ppm = 5)) %>%
    pull(Compound.Name) %>% setdiff(stans_df[i, "Compound.Name"])
  if(length(other_stans)){
    print("Other standards with this mass:")
    print(paste(other_stans, collapse = ", "))
  }
  
  mg <- molecule_guesses %>%
    filter(mean_mz%between%pmppm(mass_i, ppm=5)) %>%
    select(c(1:5, 22:23))
  print(paste("Standard formula:", stans_df[i, "Emperical.Formula"]))
  if(nrow(mg)){
    print("Predicted formula(s):")
    print(select(mg, c("feature", "formula")))
  } else {
    print("No peaks found")
  }
}
```

## For each FEATURE

Check on peak quality

```{r}
feature_df <- read.csv("temp_data/features_isoadded.csv", 
                       stringsAsFactors = FALSE)
for(i in seq(1, nrow(feature_df), 20)){
  current_features <- slice(feature_df, (i):(i+19))
  eic_20 <- apply(current_features, 1, function(x){
    eic <- MS1_dt[mz%between%pmppm(as.numeric(x["mean_mz"]), ppm = 5)&
                    rt%between%(as.numeric(x["mean_rt"])+c(-50, 50))]
    if(!nrow(eic)){
      eic <- data.frame(fileid=basename(ms_files[1]), 
                        rt=500, mz=60, int=0,
                        stringsAsFactors = FALSE)
    }
    eic_metadata <- left_join(eic, metadata, by="fileid")
    cbind(feature=x["feature"], eic_metadata, row.names=NULL)
  })
  eic_all <- do.call(rbind, eic_20)
  gp <- ggplot() + geom_line(data = eic_all, aes(x=rt, y=int, group=fileid, color=depth)) +
    facet_wrap(~feature, scales = "free") +
    scale_color_manual(values = c("25m"="#0000FF99", "Blank"="#FF000099", 
                                  "DCM"="#00FF0099", "Pooled"="#00000099",
                                  "Std"="#00000099"), 
                       name="Depth") + theme_void() +
    geom_text(data = current_features, aes(x=Inf, y=Inf, label=round(mean_q)),
              hjust=1, vjust=1)
  print(gp)
}
```
